main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('informasiku/', views.informasiku, name='informasiku'),
]

story7/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story8/', include('story8.urls')),
    ]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('daftar_buku/', views.daftar_buku, name='daftar_buku'),
    path('daftar_buku/hasil/', views.hasil),
]

main/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import *


context = {}
def home(request):
	return render(request,'main/home.html',context)

def informasiku(request):
	return render(request,'main/informasiku.html',context)

story8/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
import requests
import json


context = {}
def daftar_buku(request):
	return render(request,'story8/daftarbuku.html',context)

def hasil(request):
	my_request = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q'])
	my_content = my_request.content
	my_data = json.loads(my_content)
	return JsonResponse(my_data, safe=False)

main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Home</title>
<link rel="stylesheet" href="{% static 'css/mainstyle.css' %}" />
{% endblock meta %}

{% block content %}
    <div class="container">
	<h1>Hello, ini about</h1>
    </div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Home</title>
<link rel="stylesheet" href="{% static 'css/mainstyle.css' %}" />
{% endblock meta %}

{% block content %}
    <div class="container">
	<h1>Hello, welcome to my website!</h1>
    </div>
{% endblock content %}

main/templates/main/informasiku.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Home</title>
<link rel="stylesheet" href="{% static 'css/mainstyle.css' %}" />
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- jqurey code -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
	$(document).ready(function(){
	  $(".fa").click(function(){
       // self clicking close
       	if($(this).next(".card-body").hasClass("active")){
       		$(this).next(".card-body").removeClass("active").slideUp()
        	$(this).children("span").removeClass("fa-minus").addClass("fa-plus")
       	}
	  	else{
	   		$(".card .card-body").removeClass("active").slideUp()
	   		$(".card .card-header span").removeClass("fa-minus").addClass("fa-plus");
       		$(this).next(".card-body").addClass("active").slideDown()
       		$(this).children("span").removeClass("fa-plus").addClass("fa-minus")
	  	}
	  })
$('#accordion-button-up').click(function () {
        var thisAccordion = $(this).parent().parent().parent();
        thisAccordion.insertBefore(thisAccordion.prev());
    })

    $('#accordion-button-down').click(function () {
        var thisAccordion = $(this).parent().parent().parent();
        thisAccordion.insertAfter(thisAccordion.next());
    })
		
	})
</script>
{% endblock meta %}

{% block content %}
<div class="accordian">

  	  <div class="card">
  	  	  <div class="card-header" id="top1">
  	  	  	 <h3>Aktivitas Saat Ini </h3>
  	  	  	 <span class="fa fa-minus"></span>
  	  	  </div>
  	  	  <div class="card-body active">
  	  	  	<p>Kuliah</p>
			<br>
			<p>Main musik</p>
			<br>
			<p>Membuat program</p>
  	  	  </div>
  	  </div>

  	  <div class="card">
  	  	  <div class="card-header" id="top2">
  	  	  	 <h3>Prestasi</h3>
  	  	  	 <span class="fa fa-plus"></span>
  	  	  </div>
  	  	  <div class="card-body">
  	  	  	<p>Diterima di Universitas Indonesia</p>
			<br>
			<p>Mendapat Gold Medal 3 pada lomba paduan suara Singapur</p>
			<br>
			<p>Mendapat nilai Ujian Nasional yang memuaskan</p>
  	  	  </div>
  	  </div>

  	  <div class="card">
  	  	  <div class="card-header" id="top3">
  	  	  	 <h3>Kepanitiaan</h3>
  	  	  	 <span class="fa fa-plus"></span>
  	  	  </div>
  	  	  <div class="card-body">
  	  	  	<p>Wakil Ketua COOL</p>
			<br>
			<p>Tim pelayanan 3DG, khususnya sebagai singer dan pemain musik</p>
			<br>
			<p>Tim silabus dan mentor DDP0</p>
  	  	  </div>
  	  </div>

	  <div class="card">
  	  	  <div class="card-header" id="top4">
  	  	  	 <h3>Makanan favorit</h3>
  	  	  	 <span class="fa fa-plus"></span>
  	  	  </div>
  	  	  <div class="card-body">
  	  	  	<p>Nasi goreng seafood</p>
			<br>
			<p>Tumis brokoli</p>
			<br>
			<p>Ayam goreng saus tiram</p>
  	  	  </div>
  	    </div>
  </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
	<header>
		<nav>
			<ul class="mynav">
				<li><a href="{% url 'main:home' %}">Home</a></li>
				<li><a href="{% url 'main:informasiku' %}">My Information</a></li>
        <li><a href="{% url 'story8:daftar_buku' %}">Daftar Buku</a></li>
			</ul>
		</nav>
	</header>
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/story8/daftarbuku.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Buku</title>
<link rel="stylesheet" href="{% static 'css/buku_style.css' %}" />
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function(){
    	$("#cari").keyup(function(){
    		var my_value = $("#cari").val();
    		console.log(my_value);

    		$.ajax({
    			url: 'hasil/?q=' + my_value,
    			success: function(data) {
    				var my_array = data.items;
    				var nomor = "Nomor"
    				var myjudul = "Judul"
    				var mygambar = "Gambar"
    				console.log(my_array);
    				$("#hasil").empty();
    				$("#hasil").append("<tr><th>" + nomor + "</th>" + "<th>" +  myjudul + "</th>" + "<th>" + mygambar + "</th></tr>")
    				for(i = 1; i < my_array.length+1; i++) {
    					var judul = my_array[i-1].volumeInfo.title;
    					var gambar = my_array[i-1].volumeInfo.imageLinks.smallThumbnail;
    					var mylink = my_array[i-1].volumeInfo.infoLink
    					$("#hasil").append("<tr><td>" + i + "</td>" + "<td><a href=" + "'" + mylink + "'"+ ">" + judul + "</a></td>" + "<td>" + "<br><img src=" + gambar + "></td></tr>");
    				}
    			}
    		});
    	});
    });	
    </script>
{% endblock meta %}

{% block content %}
    <div class="dbuku">
    	<br>
	`	<input id="cari" placeholder="Silahkan masukkan kata kunci">
		<br>
		<br>
		<table id="hasil" style="width:80%; text-align: center; margin-left: auto;margin-right: auto;">
		</table>
    </div>
{% endblock content %}